BATCH_SIZE: 16
SEED: 42
DATASET: FastImageDataset
TRANSFORMS_PATH: config/transforms_config.yaml

MODEL_A: 
  name: EfficientNetV2MArcFaceModel

MODEL_B:
  name: ResNeSt50ArcFaceModel

MODEL_C:
  name: ConvNeXtArcFaceSingleModel

MODEL_D:
  name: SwinTransformerArcFaceModel
