BATCH_SIZE: 16
EPOCHS: 100
LEARNING_RATE: 0.0001
SEED: 42
patience: 10 # 조기 종료
delta: 0.01 # 개선이라고 간주하는 값
DATASET: FastImageDataset
MODEL: EfficientNetB3Model
TRANSFORMS_PATH: config/transforms_config.yaml

scheduler:
  name: cosine_warm_restart
  params: {
        T_0: 10,
        T_mult: 2,
        eta_min: 0.000001,
    }