transforms:
  # 학습 데이터용 변환 파이프라인
  train:
    # 1단계: Augraphy로 문서의 물리적/광학적 품질 저하 시뮬레이션
    - backend: augraphy
      name: OneOf
      params:
        p: 0.5 # 50% 확률로 아래 잉크 관련 증강 중 하나 적용
        transforms:
          - backend: augraphy
            name: InkBleed
            params: { intensity_range: [0.1, 0.3] }
          - backend: augraphy
            name: LowInkRandomLines
    - backend: augraphy
      name: BleedThrough
      params: { p: 0.4 }
    - backend: augraphy
      name: DirtyDrum
    - backend: augraphy
      name: LowLightNoise
    - backend: augraphy
      name: LightingGradient
    - backend: augraphy
      name: BadPhotoCopy
    - backend: augraphy
      name: ShadowCast

    # 2단계: Albumentations로 기하학적/색상 증강
    - backend: albumentations
      name: ShiftScaleRotate
      params: { p: 0.5, shift_limit: 0.05, scale_limit: 0.05, rotate_limit: 10, border_mode: 0 }
    - backend: albumentations
      name: VerticalFlip
      params: {p: 0.5}
    - backend: albumentations
      name: HorizontalFlip
      params: {p: 0.5}
    - backend: albumentations
      name: RandomBrightnessContrast
      params: { p: 0.3 }
    - backend: albumentations 
      name: Resize
      params: { height: 640, width: 640 } # 모델에 맞는 최종 입력 크기
    - backend: albumentations
      name: RandomRotate90
      params: { p: 0.5 }
    - backend: albumentations
      name: ColorJitter
      params: { p: 0.5, brightness: 0.2, contrast: 0.2, saturation: 0.2, hue: 0.2 }

    # 3단계: Torchvision으로 최종 텐서 변환 및 정규화
    - backend: torchvision
      name: ToTensor
    - backend: torchvision
      name: Normalize
      params:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

  # 검증/테스트 데이터용 변환 파이프라인
  val:
    - backend: augraphy
      name: OneOf
      params:
        p: 0.5 # 50% 확률로 아래 잉크 관련 증강 중 하나 적용
        transforms:
          - backend: augraphy
            name: InkBleed
            params: { intensity_range: [0.1, 0.3] }
          - backend: augraphy
            name: LowInkRandomLines
    - backend: augraphy
      name: DirtyDrum
    - backend: augraphy
      name: LowLightNoise
    - backend: augraphy
      name: LightingGradient
    - backend: augraphy
      name: BadPhotoCopy
    - backend: augraphy
      name: ShadowCast

    - backend: torchvision
      name: Resize
      params: { size: 640 }
    - backend: torchvision
      name: CenterCrop
      params: { size: 640 }
    - backend: torchvision
      name: RandomRotation
      params: { degrees: 360 }
    - backend: torchvision
      name: ToTensor
    - backend: torchvision
      name: Normalize
      params:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

  test:
    - backend: torchvision
      name: Resize
      params: { size: 640 }
    - backend: torchvision
      name: CenterCrop
      params: { size: 640 }
    - backend: torchvision
      name: ToTensor
    - backend: torchvision
      name: Normalize
      params:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]