transforms:
  # 학습 데이터용 변환 파이프라인
  train:
    # 1단계: Augraphy로 문서의 물리적/광학적 품질 저하 시뮬레이션
    - backend: augraphy
      name: OneOf
      params:
        p: 0.5 # 50% 확률로 아래 잉크 관련 증강 중 하나 적용
        transforms:
          - backend: augraphy
            name: InkBleed
            params: { intensity_range: [0.1, 0.3] }
          - backend: augraphy
            name: LowInkRandomLines
    - backend: augraphy
      name: BleedThrough
    - backend: augraphy
      name: OneOf
      params:
        p: 0.5
        transforms:
          - backend: augraphy
            name: DirtyDrum
          - backend: augraphy
            name: BadPhotoCopy
    - backend: augraphy
      name: OneOf
      params:
        p: 0.4
        transforms:
          - backend: augraphy
            name: SubtleNoise
          - backend: augraphy
            name: LowLightNoise
          - backend: augraphy
            name: NoiseTexturize
    - backend: augraphy
      name: LightingGradient
      params: { p: 0.5 }
    - backend: augraphy
      name: OneOf
      params:
        p: 0.5
        transforms:
          - backend: augraphy
            name: Folding
            params: 
              fold_count: 1
              fold_noise: 0.0
              fold_angle_range: [-5, 5]
              gradient_width: [0.1, 0.2]
              gradient_height: [0.01, 0.03]
              backdrop_color:
                _resolve_:
                  type: "tuple"
                  value: [255, 255, 255]
              p: 1.0

    - backend: augraphy
      name: Geometric
      params: {
        scale: [0.9, 1.1],   # 이미지 크기를 90% ~ 110%로 조절
        p: 1.0
        }
    - backend: augraphy
      name: ShadowCast
      params: {
        shadow_side: "random",       # 랜덤 방향
        shadow_opacity_range: [0.05, 0.15],
        shadow_width_range: [0.3, 0.6],
        shadow_vertices_range: [1, 3],  # 그림자 모양의 꼭짓점 개수를 1~3개로 설정
        p: 0.5
      }

    # 2단계: Albumentations로 기하학적/색상 증강
    - backend: albumentations
      name: ShiftScaleRotate
      params: { p: 0.5, shift_limit: 0.05, scale_limit: 0.05, rotate_limit: 10, border_mode: 0 }
    - backend: albumentations
      name: VerticalFlip
      params: {p: 0.5}
    - backend: albumentations
      name: HorizontalFlip
      params: {p: 0.5}
    - backend: albumentations
      name: RandomBrightnessContrast
      params: { p: 0.3 }
    - backend: albumentations
      name: OneOf
      params:
        p: 0.5
        transforms:
        - backend: albumentations
          name: RandomRotate90
          params: { p: 0.5 }
        - backend: albumentations
          name: Rotate
          params: { p: 0.5, limit: 90, border_mode: 0}
    - backend: albumentations
      name: ColorJitter
      params: { p: 0.5, brightness: 0.2, contrast: 0.2, saturation: 0.2, hue: 0.2 }
    - backend: albumentations
      name: ImageCompression
      params: { 
        quality_lower: 40, 
        quality_upper: 80, 
        compression_type: 0,  # 또는 1
        p: 0.5
        }

    # 3단계: Torchvision으로 최종 텐서 변환 및 정규화
    - backend: albumentations 
      name: Resize
      params: { height: 640, width: 640 } # 모델에 맞는 최종 입력 크기
    - backend: torchvision
      name: ToTensor
    - backend: torchvision
      name: Normalize
      params:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

  # 검증/테스트 데이터용 변환 파이프라인
  val:
    - backend: augraphy
      name: OneOf
      params:
        p: 0.5 # 50% 확률로 아래 잉크 관련 증강 중 하나 적용
        transforms:
          - backend: augraphy
            name: InkBleed
            params: { intensity_range: [0.1, 0.3] }
          - backend: augraphy
            name: LowInkRandomLines
    - backend: augraphy
      name: BleedThrough
    - backend: augraphy
      name: OneOf
      params:
        p: 0.5
        transforms:
          - backend: augraphy
            name: DirtyDrum
          - backend: augraphy
            name: BadPhotoCopy
          - backend: augraphy
            name: ShadowCast
    - backend: augraphy
      name: OneOf
      params:
        p: 0.4
        transforms:
          - backend: augraphy
            name: SubtleNoise
          - backend: augraphy
            name: LowLightNoise
          - backend: augraphy
            name: NoiseTexturize
    - backend: augraphy
      name: LightingGradient
    - backend: albumentations
      name: OneOf
      params:
        p: 0.5
        transforms:
        - backend: albumentations
          name: RandomRotate90
        - backend: albumentations
          name: Rotate
          params: { limit: 90, border_mode: 0}

    - backend: albumentations
      name: Resize
      params: { height: 640, width: 640 }
    - backend: albumentations
      name: CenterCrop
      params: { height: 640, width: 640 }
    - backend: torchvision
      name: ToTensor
    - backend: torchvision
      name: Normalize
      params:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

  test:
    - backend: albumentations
      name: Resize
      params: { height: 640, width: 640 }
    - backend: albumentations
      name: CenterCrop
      params: { height: 640, width: 640 }
    - backend: torchvision
      name: ToTensor
    - backend: torchvision
      name: Normalize
      params:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]